# Generated by Django 2.2 on 2020-07-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name': '财务表', 'verbose_name_plural': '财务表'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单信息表', 'verbose_name_plural': '订单信息表'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '类型表', 'verbose_name_plural': '类型表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': '家政人员信息表', 'verbose_name_plural': '家政人员信息表'},
        ),
        migrations.AlterField(
            model_name='finance',
            name='income',
            field=models.FloatField(verbose_name='员工净收入'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Order', verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='platform_cost',
            field=models.FloatField(verbose_name='平台收入'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_experience',
            field=models.CharField(max_length=50, verbose_name='工作经验'),
        ),
    ]
